version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=14253678
      - POSTGRES_DB=st_db

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
      - .env.test
    depends_on:
      - postgres

volumes:
  node_modules:
