version: "2"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=14253678
      - POSTGRES_DB=st_db
    restart: always

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

volumes:
  node_modules:
