# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test:
      # Primary container image where all commands run
    docker:
    # Service container image
      - image: postgres:alpine
        environment:
          POSTGRES_USER=admin
          POSTGRES_PASSWORD=14253678
          POSTGRES_DB=st_db
      - image: node:18

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout             
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run unit tests
      - run:
          command: yarn start:production
          name: Start server
          background: true
      - run:
          command: sleep 5 && curl -I localhost:3000
          name: Verify server is running

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test_app:
    jobs:
      - build_and_test