FROM node:18-alpine3.18 AS build

WORKDIR /app

COPY . .

RUN yarn add global nodemon && yarn

FROM node:18-alpine3.18

WORKDIR /app

COPY --from=build /app .

RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start:production" ]
